version: "3"

services:
  mongodb:
    image: mongo:6
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017 # binding --> local port : container port
    environment:
      MONGOBD_DATABASE: test
    volumes:
      - ./mongodb:/data/db # binding --> local dir : container dir
